name: Angelic
favicon: null
layout_spectrum: 0.39081605267710984
typography_spectrum: 0.344038573326543
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.4715554832946509
  lightness: 0.5894396668300033
  saturation: 0.8180790066253394
  rhythmicContrast: 0.7475538088474423
purpose: []
